before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - main: ./main.go
    id: turtle
    binary: turtle
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: turtle
    builds:
      - turtle
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

nfpms:
  - id: turtle
    maintainer: omarahm3 <me@mrg.sh>
    description: Rsync wrapper to do multiple transfers from a single yaml file
    homepage: https://github.com/omarahm3/turtle
    license: MIT
    package_name: turtle
    builds:
      - turtle
    formats:
      - deb
      - rpm
      - apk

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
